name: cowell
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.4.0
  hidden_drawer_menu: ^1.1.2
  flutter_staggered_grid_view: "^0.3.2"
  carousel_slider: ^2.2.1
  flutter_staggered_animations: "^0.1.2"
  http: ^0.12.2
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/portraits/
    - assets/img/avatars/
    - assets/icon/
    - assets/excel/

